services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: anki_website_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
        - "54320:5432"
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "54330:80"
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080