version: '3.8'

services:
  db:
    image: postgres:16-alpine # Use a specific version
    restart: always
    environment:
      POSTGRES_DB: anki_website_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password # Change this in your actual .env file
    ports:
      - '5432:5432' # Map host port 5432 to container port 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Persist data locally

volumes:
  postgres-data: