import type { ObjectId } from 'mongodb';

// --- Type aliases ---

export type PromptType = 'text' | 'image' | 'map';
export type AnswerType = 'self_rate' | 'type_in' | 'multi' | 'map_select';

export enum ReviewResult {
    EASY = "easy",
    MEDIUM = "medium",
    HARD = "hard",
    MISSED = "missed",
}

// --- Database/API Interfaces ---

export interface Deck {
    id: string;
    name: string;
    createdAt?: Date;
    updatedAt?: Date;
}

export interface Card {
    id: string;
    deck_id: string;
    prompt_type: PromptType;
    prompt_content: string;
    prompt_text?: string;
    answer_type: AnswerType;
    answer_content: string | string[];
    correct_index?: number;
    extra_context?: string;
    createdAt?: Date;
    updatedAt?: Date;
}

export interface ReviewEvent {
    id: string;
    card_id: string;
    result?: ReviewResult;
    timestamp: Date;
    is_correct?: boolean;
    answer_type?: AnswerType;
    user_answer?: string;
}

// --- MongoDB Document Types ---

export interface DeckDocument {
    _id: ObjectId;
    name: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface CardDocument {
    _id: ObjectId;
    deck_id: ObjectId;
    prompt_type: PromptType;
    prompt_content: string;
    prompt_text?: string;
    answer_type: AnswerType;
    answer_content: string | string[];
    correct_index?: number;
    extra_context?: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface ReviewEventDocument {
    _id: ObjectId;
    card_id: ObjectId;
    result?: ReviewResult;
    timestamp: Date;
    is_correct?: boolean;
    answer_type?: AnswerType;
    user_answer?: string;
}

// --- Utility/Auth Types ---

export interface JwtPayload {
    user: string;
    iat?: number;
    exp?: number;
}


export interface SingleImportCardData {
    front: string;
    back: string;
}

export interface ReviewHistoryEntry {
    eventId: string;
    cardId: string;
    cardFront: string;
    cardBack: string;
    result?: ReviewResult;
    timestamp: Date;
    is_correct?: boolean;
    answer_type?: AnswerType;
    user_answer?: string;
}

// --- AI Quiz Types ---

export interface QuestionAnswerPair {
    question_text: string;
    answer_text: string;
    extra_context?: string;
}

// Represents the structure stored in the 'quiz_sets' MongoDB collection
export interface QuizSetDocument {
    _id?: ObjectId;         // Optional because it's generated by MongoDB
    topic: string;
    questions: QuestionAnswerPair[]; // Array of question/answer objects
    createdAt: Date;
}

// Client-facing type after mapping _id to id
export interface QuizSet {
    id: string;
    topic: string;
    questions: QuestionAnswerPair[];
    createdAt: Date;
}

// Represents the structure stored in the 'quiz_attempts' MongoDB collection
export interface QuizAttemptDocument {
    _id?: ObjectId;
    quiz_set_id: ObjectId;  // Link to the QuizSetDocument
    question_index: number; // 0-based index of the question in the set
    user_answer: string;
    is_correct: boolean;
    llm_rationale?: string; // Optional explanation from the scoring LLM
    createdAt: Date;
}

// Client-facing type (potentially, might not be needed if only scoring result is returned)
export interface QuizAttempt {
    id: string;
    quiz_set_id: string;
    question_index: number;
    user_answer: string;
    is_correct: boolean;
    llm_rationale?: string;
    createdAt: Date;
}

// --- Reading Comprehension Types ---

export interface ReadingComprehensionQuestion {
    question_text: string;
    correct_answer: string;
}

export interface ReadingSessionDocument {
    _id?: ObjectId;
    topic: string;
    passage: string;
    questions: ReadingComprehensionQuestion[];
    user_id?: string; // Optional for future user association
    createdAt: Date;
}

export interface ReadingSession {
    id: string;
    topic: string;
    passage: string;
    questions: ReadingComprehensionQuestion[];
    user_id?: string;
    createdAt: Date;
}

export interface ReadingAttemptDocument {
    _id?: ObjectId;
    session_id: ObjectId;
    reading_time_ms: number; // Time spent reading the passage
    answers: {
        question_index: number;
        user_answer: string;
        is_correct: boolean;
        overridden?: boolean; // User corrected the AI scoring
    }[];
    total_score: number; // Calculated score out of total questions
    createdAt: Date;
}

export interface ReadingAttempt {
    id: string;
    session_id: string;
    reading_time_ms: number;
    answers: {
        question_index: number;
        user_answer: string;
        is_correct: boolean;
        overridden?: boolean;
    }[];
    total_score: number;
    createdAt: Date;
}

// --- AI Chat Types ---

export interface AIChatToolCall {
    id: string;
    name: string;
    arguments: unknown;
    approved: boolean;
    executedAt?: Date;
    result?: unknown;
    error?: string;
}

export interface AIChatMessageDocument {
    _id?: ObjectId;
    session_id: ObjectId;
    role: 'user' | 'assistant' | 'system' | 'tool';
    content: string; // serialized text or JSON
    tool_calls?: AIChatToolCall[];
    createdAt: Date;
}

export interface AIChatMessage {
    id: string;
    role: 'user' | 'assistant' | 'system' | 'tool';
    content: string;
    tool_calls?: AIChatToolCall[];
    createdAt: Date;
}

export interface AIChatSessionDocument {
    _id?: ObjectId;
    user_id?: string;
    title?: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface AIChatSession {
    id: string;
    user_id?: string;
    title?: string;
    createdAt: Date;
    updatedAt: Date;
}

// --- Speed Reading Types ---

export interface SpeedReadingAttemptDocument {
    _id?: ObjectId;
    text_hash: string;
    text_excerpt: string; // first 200 chars for reference
    text_words: number;
    text_chars: number;
    wpm: number;
    duration_ms: number;
    perceived_comprehension: number; // 1-10
    createdAt: Date;
}

export interface SpeedReadingAttempt {
    id: string;
    text_hash: string;
    text_excerpt: string;
    text_words: number;
    text_chars: number;
    wpm: number;
    duration_ms: number;
    perceived_comprehension: number;
    createdAt: Date;
}
